[global]
fsid = b601c2b8-11c2-4337-b333-65102b5e9474
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
osd_pool_default_size = 3
osd_pool_default_min_size = 1
osd_pool_default_pg_num = 128
mon_allow_pool_delete = true
mon_allow_pool_size_one = true
ms_type = async+posix
mon_initial_members = ggpu102
mon_host = 10.245.148.5

[osd]
osd_max_object_size = 137438953472
osd_crush_chooseleaf_type = 1
osd_objectstore = memstore
memstore_device_bytes = 25769803776
osd_class_update_on_start = false

[client.bench]
key = AQDh4ktpaMWNJRAAt9deW1Xetk/emKnclSlhug==
caps mds = "allow *"
caps mgr = "allow *"
caps mon = "allow *"
caps osd = "allow *"

[mon.ggpu102]
public_addr = 10.245.148.5

[client.admin]
key = AQBoDKpoopiUBhAAyyMJFQCETvpLgcrKNVkVSQ==
caps mon = allow *
caps mgr = allow *
caps osd = allow *
caps mds = allow *

