[global]
fsid = b601c2b8-11c2-4337-b333-65102b5e9474
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
osd_pool_default_size = 3
osd_pool_default_min_size = 1
osd_pool_default_pg_num = 128
mon_allow_pool_delete = true
mon_allow_pool_size_one = true
ms_type = async+posix

[osd]
osd_max_object_size = 137438953472
osd_crush_chooseleaf_type = 1
osd_objectstore = memstore
osd_class_update_on_start = false